config/routes.rb
Rails.application.routes.draw do

  root 'hispanicsincomputing#index'

  get 'members', to: 'hispanicsincomputing#members'
  get 'map'   => 'hispanicsincomputing#map',  :as => 'map'

  get  'tapia2018'   => 'hispanicsincomputing#tapia_2018',  :as => 'conference_2018'
  get  'tapia2017'   => 'hispanicsincomputing#tapia_2017',  :as => 'conference_2017'
  get  'tapia2016'   => 'hispanicsincomputing#tapia_2016',  :as => 'conference_2016'
  get  'tapia2013'   => 'hispanicsincomputing#tapia_2013',  :as => 'conference_2013'

  get  'profile/edit'  => 'posts#new', :as => "add_info"
  get  'profile'  => 'posts#show', :as => "get_info"
  post 'update_info'  => 'posts#update'

  get 'auth/google/callback' => 'sessions#create'
  post 'logout' => 'sessions#destroy'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :email
  before_save :validate_location_for_map

  def self.validate_and_create(auth)
    email = auth[:info][:email]
    if User.valid_user?(email)
      user = User.find_by(:email => email) || User.new(:first_name => auth[:info][:first_name],
                      :last_name => auth[:info][:last_name],
                      :email => auth[:info][:email])
      return user.save ? user : nil
    else
      return nil
    end
  end

  def self.valid_user?(email)
    return false if email.nil?
    begin
      Slack::Web::Client.new.users_lookupByEmail(:email => email)
      return true
    rescue Slack::Web::Api::Errors::SlackError
      return false
    end
  end

  def valid_map_user?
    not Geocoder.search(self.location).empty?
  end

  def validate_location_for_map
    if self.map_visibility && (not valid_map_user?)
      self.map_visibility = false
    end
    return true
  end

  def country_of_origin_to_array
    if self.country_of_origin.nil?
      return []
    else
      return self.country_of_origin.split(" ")
    end
  end
end

app/controllers/application_controller.rb
require 'optparse'
require 'open-uri'
require 'json'
require 'csv'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user

  protected
  def current_user
    @current_user ||= User.find_by(:id => session[:id])
  end

  def check_current_user
    unless current_user
      flash[:danger] = "You must login to gain access to that page"
      redirect_to members_path and return
    end
  end
	
end

app/controllers/hispanicsincomputing_controller.rb
class HispanicsincomputingController < ApplicationController
  def index
  end

  def members
  end

  def tapia_2018
  end

  def tapia_2017
  end

  def tapia_2016
  end

  def tapia_2013
  end

  def modify_data
  end

  def map
    all_map_users = User.where(map_visibility: true)
    gon.all_users = all_map_users

    @locations = []
    all_map_users.each do |user|
      @locations << Geocoder.search(user.location).first.coordinates
    end
    @user_num = @locations.length
    gon.locations = @locations
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :check_current_user, :except => [:filter_and_modify_params, :visibility_modified?]

  def new
  end

  def show
  end

  def update
    filtered_params = filter_and_modify_params(params)
    success = @current_user.update(filtered_params)
    if visibility_modified?(success, filtered_params[:map_visibility])
      flash[:warning] = "Unable to add pin to map:" \
                        " Location must be the name" \
                        " of a city in order for a pin" \
                        " to be visible on the map"

    elsif success
      flash[:success] = "Update successful"
    else
      flash[:error] = "Update unsuccessful"
    end
    redirect_to get_info_path
  end

  private
  def filter_and_modify_params(params)
    filtered_params = params
            .require(:current_user)
            .permit(:first_name,
                    :last_name,
                    :location,
                    {:country_of_origin => []},
                    :map_visibility,
                    :photo_link,
                    :profession,
                    :linkedin,
                    :organization)
    if filtered_params[:country_of_origin]
      filtered_params[:country_of_origin] = 
        filtered_params[:country_of_origin].join(" ")
    end
    return filtered_params
  end

  def visibility_modified?(success, params_map_visibility)
    success && (params_map_visibility.to_i == 1) && (not @current_user.map_visibility)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController  
  def create
    user = User.validate_and_create(env["omniauth.auth"])
    if user.nil?
      flash[:error] = "Login unsuccessful: Please use " \
                      "the same email that you use for " \
                      "the Hispanics in Engineering Slack group"
    else
      session[:id] = user.id
      flash[:success] = "Login successful"
    end
    redirect_to root_path
  end

  def destroy
    reset_session
    flash[:success] = "Logout successful"
    redirect_to members_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
        class: "alert fade in alert-#{type} #{tag_class}"
      }.merge(options)

      close_button = content_tag(:button, raw("&times;"), type: "button", class: "close", "data-dismiss" => "alert")

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg, tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/hispanicsincomputing_helper.rb
module HispanicsincomputingHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/hispanicsincomputing/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hispanics in Computing</title>
    <%= stylesheet_link_tag "theme-css/bootstrap-responsive" %>
    <%= stylesheet_link_tag "theme-css/style" %>
    <%= stylesheet_link_tag "theme-css/default" %>
</head>
<body>
  <!-- Header area -->
  <div class="container" id="header-container">
    <%= image_tag("tapia-2018/2018.jpg", :alt => "Tapia 2018", :classes => "img-responsive") %>
    <p>
      Tapia Conference 2018
    </p>
  </div>
  <!-- section: about -->
  <section id="about" class="section">
    <div class="container">
      <h4>Who We Are</h4>
      <div class="row-fluid">
        <div class="span">
          <div>
            <p>
              We are a group of Latinx/Hispanics that are interested or work in computing. <br>
              Our group includes industry representatives, faculty, researchers, students, and others.
            </p>
            <h1>The sole purpose of our group is to serve as mentors and sponsors <br>
              for other Latinx/Hispanics interested in computing.</h1>
          </div>
        </div>
      </div>
    </div>
    <!-- /.container -->
  </section>
  <!-- end section: about -->
  <!-- section: events -->
  <section id="events" class="section">
    <div class="container">
      <h4>Upcoming Events</h4>
      <div class="row-fluid">
        <div class="span">
          <p>
            We will have our annual gathering at the Tapia Conference in San Diego on, join us?
          </p>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="span4 offset1">
            <p>
              <strong>BOF:</strong> <a href="http://tapiaconference.org/schedule/
              thursday-september-19-2019/300pm-400pm/hispanics-in-computing-community/"
              > Hispanics in Computing Community</a><br>
              <strong>Date:</strong> Thursday, September 19, 2019 <br>
              <strong>Time:</strong> 3:00PM - 4:00PM <br>
              <strong>Location:</strong> San Diego A <br>
            </p>
        </div>
        <div class="span6">
          <p>
            <strong>Presenters:</strong> Patricia Ordóñez, University of Puerto Rico Río Piedras<br>
            Nery Chapetón-Lamas, MiraCosta College<br>
            Juan F. Sequeda, Capsenta<br>
            Brianna Posadas, University of Florida<br>
          </p>
        </div>
      </div>
    </div>
    <div class="container">
			<div class="row">
				<div class="span">
					<blockquote class="small">
						<strong> Abstract: </strong> The Hispanics in Computing community was
            founded a few
            months before the Tapia 2009 Conference. Since then, the group
            has been meeting at this annual conference. The group has grown
            in numbers and online presence (
            <a href="https://www.facebook.com/groups/HispanicsInComputing/"
            target="_blank">Facebook
            </a>,<a href="https://www.linkedin.com/groups/6962622"
            target="_blank"> LinkedIn </a>, and
            <a href="#">http://www.hispanicsincomputing.com/</a>). The impact of this
            gathering in our community has been tremendous. Several members
            of the community that attended our BoF as young graduate students
             are now in tenure track positions or employed in research organizations.
             Once again, we propose to hold our annual BoF at the Tapia Conference.
             The gathering will allow many of us to meet face to face and discuss
             issues facing Hispanics. As the undergraduate population attending
             Tapia grows, it is important to serve as mentors for the new students
             starting their careers in computing. The goal for this year’s gathering
             is to explore how to do virtual mentoring to help increase ties within
             the community.
					</blockquote>
				</div>
			</div>
		</div>
  </section>
  <!-- end section: events -->
</body>
</html>

app/views/hispanicsincomputing/map.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Interactive Members Map</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.1/dist/leaflet.css" />
    <%= stylesheet_link_tag "map" %>
    <%= include_gon(:init => true) %>
  </head>
  <body class="map">
  <!-- Header area -->
   <div class="header">
      <h1 style="text-align:center">Interactive Members Map</h1>
   </div>
   <div id="map-container">
     <div id="leaflet-map"></div>
     <p style="text-align:right">Current number of members: <%= @user_num %></p>
  </div>
  <script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet.js"></script>
  <script src='https://api.mapbox.com/mapbox.js/v3.2.1/mapbox.js'></script>
  <%= javascript_include_tag "map" %>
  </body>
</html>

app/views/hispanicsincomputing/members.html.erb
<!DOCTYPE html>
<html>
<body>
<section id="members" class="section">
  <div class="container login-wrapper">
    <i class="icon-circled icon-bgdark icon-user icon-2x"></i>
    <h4>Members Login</h4>
    <a href="/auth/google" class="btn btn-primary btn-larg">Connect to Google</a>
  </div>
</section>
</body>
</html>

app/views/hispanicsincomputing/tapia_2013.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Tapia 2013</title>
  </head>
  <body class="tapia">
    <!-- Header area -->
   <div class="container">
      <h1>Tapia 2013, Washington DC</h1>
      <%= image_tag("tapia-2013/2013.jpg", :alt => "Attendees at the 2013 Tapia Conference", :classes => "img-responsive") %>
    </div>

    <!-- Photos Section -->
    <section class="section" id="about">
      <div class="container">
        <h3>Pizza afterwards</h3>
        <div class="row">
          <div class="span2 thumbnail">
            <%= image_tag("tapia-2013/pizza-1.jpg", :alt => "Attendees eating pizza", :classes => "img-responsive") %>
          </div>
          <div class="span2 thumbnail">
            <%= image_tag("tapia-2013/pizza-2.jpg", :alt => "Attendees eating pizza", :classes => "img-responsive") %>
          </div>
          <div class="span2 thumbnail">
            <%= image_tag("tapia-2013/pizza-3.jpg", :alt => "Attendees eating pizza", :classes => "img-responsive") %>
          </div>
          <div class="span2 thumbnail">
            <%= image_tag("tapia-2013/pizza-4.jpg", :alt => "Attendees eating pizza", :classes => "img-responsive") %>
          </div>
          <div class="span2 thumbnail">
            <%= image_tag("tapia-2013/pizza-5.jpg", :alt => "Attendees eating pizza", :classes => "img-responsive") %>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/hispanicsincomputing/tapia_2016.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Tapia 2016</title>
  </head>
  <body class="tapia">
    <!-- Header area -->
   <div class="container">
      <h1>Tapia 2016, Austin, TX</h1>
      <%= image_tag("tapia-2016/2016.jpg", :alt => "Attendees at the 2016 Tapia Conference", :classes => "img-responsive") %>
    </div>

    <!-- Videos Section -->
    <section class="section" id="about">
      <div class="container">
        <h3>Las Banderas…</h3>
        <iframe src="https://www.youtube.com/embed/hmoWxLrVp1g" allow="autoplay; encrypted-media" allowfullscreen="" width="560" height="315" frameborder="0"></iframe>
      </div>
    </section>
  </body>
</html>

app/views/hispanicsincomputing/tapia_2017.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Tapia 2017</title>
  </head>
  <body class="tapia">
  <!-- Header area -->
   <div class="container">
      <h1>Tapia 2017, Atlanta, GA</h1>
      <%= image_tag("tapia-2017/2017.jpg", :alt => "Attendees at the 2017 Tapia Conference", :classes => "img-responsive") %>
    </div>
  </body>
</html>

app/views/hispanicsincomputing/tapia_2018.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Tapia 2018</title>
  </head>

  <body class="tapia">
  <!-- Header area -->
   <div class="container">
      <h1>Tapia 2018 in Orlando, FL</h1>
      <%= image_tag("tapia-2018/2018.jpg", :alt => "Attendees at the 2018 Tapia Conference", :classes => "img-responsive") %>
    </div>

    <section class="section" id="about">
      <div>
        <p>Hope you were able to join us at the
          <a href="http://tapiaconference.org">2018 Tapia Conference</a>
          in Orlando, September 19-22, 2018. <br>
          Our <a href="http://www.tapiaconference.org/schedule/thursday-september-20-2018/500pm-600pm/hispanics-in-computing/">
            Birds of a Feather
          </a> event was on Thursday September 20th followed by a <br>
          <a href="http://www.tapiaconference.org/schedule/thursday-september-20-2018/600-pm-730-pm/reception/hispanics-in-computing-reception/">
            Hispanics in Computing Reception</a>
          sponsored by The Aerospace Corporation.</p>
        <p>We went to the Cuba Libre restaurant and had a great time. <br>
          Come join us in San Diego 2019!</p>
      </div>

    <!-- Photos Section -->
    <div class="container">
      <h3>Photos</h3>
        <div class="row">
          <div class="span4 thumbnail">
            <%= image_tag("tapia-2018/food-1.jpg", :alt => "Attendees eating at a Cuba Libre restaurant together", :classes => "img-responsive") %>
          </div>
          <div class="span4 thumbnail">
            <%= image_tag("tapia-2018/food-2.jpg", :alt => "Attendees eating at a Cuba Libre restaurant together", :classes => "img-responsive") %>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hispanics in Computing</title>
    <%= stylesheet_link_tag "theme-css/bootstrap-responsive" %>
    <%= stylesheet_link_tag "theme-css/style" %>
    <%= stylesheet_link_tag "theme-css/default" %>
    <%= stylesheet_link_tag "flags" %>
    <%= include_gon %>
</head>
<body>
  <!-- navbar -->
  <div class="navbar-wrapper">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <!-- Responsive navbar -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
        </a>
          <div class="navbar-header">
            <h1 class="brand navbar-title "><a href="/">Hispanics in Computing</a></h1>
            <% if current_user %>
              <h6 class="navbar-name"> <%= "Hello #{current_user.first_name}!" %></h6>
            <% end %>
          </div>
          <!-- navigation -->
          <nav class="pull-right nav-collapse">
            <ul id="menu-main" class="nav">
              <li><a href="/#about">About</a></li>
              <li><a href="/#events">Events</a></li>
              <li><a href="/#connect">Connect</a></li>
              <li>
                <div class="nav-item dropdown nav-outer-menu">
                  <a class="nav-link nav-menu dropdown-toggle" href="#" id="navbarDropdown"
                  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Tapia<span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu navbar-menu" >
                    <li><%= link_to "TAPIA 2018", conference_2018_path %></li>
                    <li><%= link_to "TAPIA 2017", conference_2017_path %></li>
                    <li><%= link_to "TAPIA 2016", conference_2016_path %></li>
                    <li><%= link_to "TAPIA 2013", conference_2013_path %></li>
                  </ul>
                </div>
              </li>
              <li>
                <% if current_user %>
                  <div class="nav-item dropdown nav-outer-menu">
                    <a class="nav-link nav-menu dropdown-toggle" href="#" id="navbarDropdown"
                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Members<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu navbar-menu">
                      <li><%= link_to "View Profile", get_info_path %></li>
                      <li><%= link_to "Edit Profile", add_info_path %></li>
                      <li><%= link_to "View Map", map_path %></li>
                      <li><%= button_to "Log out", logout_path , :id => "logout-button" %></li>
                    </ul>
                  </div>
                <% else %>
                  <%= link_to "Members Login", members_path %>
                <% end %>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <%= bootstrap_flash(:class => "flash-notice") %>
  <%= yield %>
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "jquery.nav" %>
  <%= javascript_include_tag "bootstrap" %>
  <%= javascript_include_tag "custom" %>

  <footer id="connect">
    <div class="container">
      <h4>Connect with us</h4>
      <div class="row">
        <div class="span6 offset3">
          <ul class="social-networks">
            <li><a href="https://www.linkedin.com/groups/6962622" target="_blank">
              <i class="icon-circled icon-bgdark icon-linkedin icon-2x"></i></a></li>
            <li><a href="https://www.facebook.com/groups/HispanicsInComputing/" target="_blank">
              <i class="icon-circled icon-bgdark icon-facebook icon-2x"></i></a></li>
            <li><a href="https://twitter.com/HispanicsInComp" target="_blank">
              <i class="icon-circled icon-bgdark icon-twitter icon-2x"></i></a></li>
            <li><a href="http://hispanicsincomputing.org/mailman/listinfo/members_hispanicsincomputing.org"
               target="_blank">
              <i class="icon-circled icon-bgdark icon-envelope icon-2x"></i></a></li>
          </ul>
          <p class="copyright">
            &copy; Hispanics in Computing 2014-today
          </p>
        </div>
      </div>
    </div>
    <!-- ./container -->
  </footer>
</body>
</html>

app/views/posts/all_data.html.erb
<!-- TODO: Call a javascript file here or in controller to parse the arguments @firstname,@lastname,@location -->
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  </body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<%= form_tag update_info_path, :method => :post do%>
  <section id="posts" class="section">
    <div class="container login-wrapper">
      <div class="profile-header">
        <h3>Edit Profile</h3>
      </div>
      <% if !@current_user.photo_link || @current_user.photo_link.empty? %>
        <%= image_tag("profile_default.jpg", :alt => "default profile picture", :class => "img-responsive img-pfp") %>
      <% else %>
        <%= image_tag(@current_user.photo_link, :alt => "profile picture", :class => "img-responsive img-pfp") %>
      <% end %>

      <div class="row profile-form">
        <div class="span">
          <%= label :current_user, :photo_link, 'Photo Link' %>
        </div>
        <div class="span3">
          <%= text_field :current_user, :photo_link %>
        </div>
      </div>
      <div class="row profile-form">
        <div class="span">
          <%= label :current_user, :first_name, 'First Name' %>
        </div>
        <div class="span3">
          <%= text_field :current_user, :first_name %>
        </div>
      </div>
      <div class="row profile-form">
        <div class="span">
          <%= label :current_user, :last_name, 'Last Name' %>
        </div>
        <div class="span3">
          <%= text_field :current_user, :last_name %>
        </div>
      </div>

      <div class="row profile-form">
        <div class="span">
          <%= label :current_user, :email, 'Email' %>
        </div>
        <div class="span3">
          <%= text_field :current_user, :email %>
        </div>
      </div>

      <div class="row profile-form">
        <div class="span">
          <%= label :current_user, :profession, 'Occupation' %>
        </div>
        <div class="span3">
          <%= select :current_user,
                     :profession,
                     ["Student", "Professor", "Professional", "Other"] %>
        </div>
      </div>

      <div class="row profile-form">
        <div class="span">
          <%= label :current_user, :linkedin, 'LinkedIn' %>
        </div>
        <div class="span3">
          <%= text_field :current_user, :linkedin %>
        </div>
      </div>

      <div class="row profile-form">
        <div class="span">
          <%= label :current_user, :organization, 'Organization' %>
        </div>
        <div class="span3">
          <%= text_field :current_user, :organization %>
        </div>
      </div>


      <div class="row profile-form">
        <div class="span">
          <%= label :current_user, :location, 'Current City' %>
        </div>
        <div class="span3">
          <%= text_field :current_user, :location %>
        </div>
      </div>
      <div class="row profile-form">
        <div class="span">
          <%= label :current_user, :country_of_origin, 'Country of Origin' %>
        </div>
        <div class="span3">
          <%= country_select :current_user,
                             :country_of_origin,
                             {:include_blank => 'Select Country/Countries',
                             :selected => current_user.country_of_origin_to_array},
                             {:multiple => true,
                              "data-toggle"=>"tooltip",
                              :title =>"Hold ctrl and click to choose multiple countries"} %>
        </div>
      </div>
      <div class="row profile-form">
        <div class="span">
          <%= label :current_user, :map_visibility, 'Visible on Map' %>
        </div>
        <div class="span3">
          <%= check_box :current_user,
                            :map_visibility,
                            :value => 1,
                            :checked => current_user.map_visibility %>
        </div>
      </div>

      <%= submit_tag 'Save Changes', :class => "btn btn-primary profile-save"%>
    </div>
  </section>
<% end %>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Profile</title>
  </head>
  <body class="profile">
    <section class="section" id="profile">
      <div class="container login-wrapper">
        <div class="profile-header">
          <h3>My Profile</h3>
          <a href=<%= add_info_path %> class="edit-profile">
            <i class="icon-square icon-bgwhite icon-pencil icon-2x"></i>
          </a>
        </div>
        <% if !@current_user.photo_link || @current_user.photo_link.empty? %>
          <%= image_tag("profile_default.jpg", :alt => "default profile picture", :class => "img-responsive img-pfp") %>
        <% else %>
          <%= image_tag(@current_user.photo_link, :alt => "profile picture", :class => "img-responsive img-pfp") %>
        <% end %>
        <h1><%= @current_user.first_name + " " + @current_user.last_name %></h1>
        <p><strong>Email: </strong> <%= @current_user.email %> </p>
        <p><strong>Occupation: </strong> <%= @current_user.profession %> </p>
        <p><strong>LinkedIn: </strong> <%= @current_user.linkedin %> </p>
        <p><strong>Organization: </strong> <%= @current_user.organization %> </p>
        <p><strong>Location: </strong> <%= @current_user.location %> </p>
        <p><strong>Country of origin : </strong> <%= @current_user.country_of_origin %> </p>
        <p><%= @current_user.map_visibility ? '' : 'Not' %> Visible on Map</p>
      </div>
    </section>
    </body>
</html>